#pragma config(Sensor, dgtl1,    limitSwitch,  sensorTouch)
#pragma config(Motor,  port2,           frontRight,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           backRight,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           frontLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           backLeft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           frontMangonel, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           backMangonel,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           intake,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           claw,          tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

   // Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
   // used by the competition include file, for example, you might want
   // to display your team name on the LCD in this function.
   // bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
  while(SensorValue[limitSwitch] != 1) {
    motor[frontMangonel] = 80;
    motor[backMangonel] = 80;
  }
  motor[frontMangonel] = 0;
  motor[backMangonel] = 0;
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
  // User control code here, inside the loop
  while (true)
    {
      motor[frontRight] = vexRT[Ch2];
      motor[backRight] = vexRT[Ch2];
      motor[frontLeft] = vexRT[Ch3];
      motor[backLeft] = vexRT[Ch3];
  
      if(vexRT[Btn6U]==1) {
       motor[frontMangonel] = 100;
       motor[backMangonel] = 100;
      }
      else if(vexRT[Btn6D] == 1) {
       if(SensorValue[limitSwitch] != 1) {
          motor[frontMangonel] = 80;
          motor[backMangonel] = 80;
       }
       motor[frontMangonel] = 0;
        motor[backMangonel] = 0;
      }
      else {
       motor[frontMangonel] = 0;
       motor[backMangonel] = 0;
      }
  
      if(vexRT[Btn5D] == 1) {
       motor[intake] = 127;
      }
      else if(vexRT[Btn5U] == 1) {
  
       motor[intake] = -127;
      }
      else {
       motor[intake] = 0;
      }
  
      if(vexRT[Btn8D] == 1) {
          motor[claw] = 100;
      }
      else if(vexRT[Btn8U] == 1) {
          motor[claw] = -100;
      }
      else {
          motor[claw] = 0;
      }
    }
}
