#pragma config(Sensor, in1,    potentiometer,  sensorPotentiometer)
#pragma config(Motor,  port2,           frontRight,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           backRight,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           frontLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           backLeft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           frontLauncher, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           backLauncher,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           intake,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           claw,          tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main() {
  while (true)
  {
    motor[frontRight] = vexRT[Ch2];
    motor[backRight] = vexRT[Ch2];
    motor[frontLeft] = vexRT[Ch3];
    motor[backLeft] = vexRT[Ch3];
    if(vexRT[Btn6U]==1) {
    	motor[frontLauncher] = 127;
    	motor[backLauncher] = 127;
    }
    else if(vexRT[Btn6D] == 1) {
    	while(SensorValue[potentiometer] < 550 || SensorValue[potentiometer] > 600) {
	    	motor[frontLauncher] = 70;
	    	motor[backLauncher] = 70;
	    }
    }
    else {
	    motor[frontLauncher] = 0;
	    motor[backLauncher] = 0;
    }

    if(vexRT[Btn5D] == 1) {
    	motor[intake] = 127;
    }
    else if(vexRT[Btn5U] == 1) {

    	motor[intake] = -127;
    }
    else {
    	motor[intake] = 0;
    }
  }
}
