#pragma config(Sensor, dgtl1,    limitSwitch,  sensorTouch)
#pragma config(Motor,  port2,           frontRight,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           backRight,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           frontLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           backLeft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           frontMangonel, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           backMangonel,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           intake,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           claw,          tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main() {
  int driveGear = 1;
  // User control code here, inside the loop
  while (true)
    {
      motor[frontRight] = (vexRT[Ch2])/driveGear;
      motor[backRight] = (vexRT[Ch2])/driveGear;
      motor[frontLeft] = (vexRT[Ch3])/driveGear;
      motor[backLeft] = (vexRT[Ch3])/driveGear;
  
      if(vexRT[Btn6U]==1) {
       motor[frontMangonel] = 100;
       motor[backMangonel] = 100;
      }
      else if(vexRT[Btn6D] == 1) {
       if(SensorValue[limitSwitch] != 1) {
          motor[frontMangonel] = 80;
          motor[backMangonel] = 80;
       }
      }
      else {
       motor[frontMangonel] = 0;
       motor[backMangonel] = 0;
      }
  
      if(vexRT[Btn7L] == 1) {
       motor[intake] = 127;
       wait1Msec(0090);
       motor[intake] = 0;
       wait1Msec(0500);
      }
      else if(vexRT[Btn7R] == 1) {
       motor[intake] = -127;
       wait1Msec(0090);
       motor[intake] = 0;
       wait1Msec(0500);
      }
      else {
       motor[intake] = 0;
      }
      
      if(vexRT[Btn5U] == 1) {
       motor[intake] = 40;
      }
      else if(vexRT[Btn5D] == 1) {
       motor[intake] = -40;
      }
      else {
       motor[intake] = 0;
      }
  
      //=====RIGHT SIDE OF THE REMOTE=====
      if(vexRT[Btn8D] == 1) {
          motor[claw] = 100;
      }
      else if(vexRT[Btn8U] == 1) {
          motor[claw] = -100;
      }
      else {
          motor[claw] = 0;
      }
      
      if(vexRT[Btn8R] == 1) {
      	driveGear += 1;
      	wait1Msec(0500);
    	}
    	else if((vexRT[Btn8L] == 1)&&(driveGear > 1)){
    		driveGear -= 1;
    		wait1Msec(0500);
    	}
    }
  }
}
